import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.cdnfonts.com/css/montserrat" rel="stylesheet"></link>

        <link rel="icon" type="image/svg+xml" href="/assets/images/ABR Logo 1.svg" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
